# Generated by Django 4.2.6 on 2023-10-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenuApp', '0002_alter_menu_slug_alter_menu_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='TreeMenuApp.menuitem'),
        ),
    ]
